Mutation:
    type: object
    config:
        fields:
            createCourse:
                type: "Course!"
                args:
                    input:
                        type: "CourseInput!"
                resolve: "@=mutation('createCourse', [args])"
            updateCourse:
                type: "Course!"
                args:
                    id:
                        type: "Int!"
                    input:
                        type: "CourseInput!"
                resolve: "@=mutation('updateCourse', [args])"
            deleteCourse:
                type: "Boolean!"
                args:
                    id:
                        type: "Int!"
                resolve: "@=mutation('deleteCourse', [args])"
