Query:
    type: object
    config:
        fields:
            course:
                type: "Course"
                args:
                    id:
                        type: "Int!"
                resolve: "@=resolver('CourseResolver', [args])"
            courses:
                type: "CourseConnection!"
                args:
                    limit:
                        type: "Int"
                        defaultValue: 10
                    offset:
                        type: "Int"
                        defaultValue: 0
                    sort:
                        type: "String"
                        defaultValue: "id"
                    order:
                        type: "String"
                        defaultValue: "ASC"
                    filters:
                        type: "String"
                        description: "JSON-encoded filter map (field: value)"
                resolve: "@=resolver('CoursesResolver', [args])"
